// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct BountymeshClientProgram;
impl sails_rs::client::Program for BountymeshClientProgram {}
pub trait BountymeshClient {
    type Env: sails_rs::client::GearEnv;
    fn bounty_service(
        &self,
    ) -> sails_rs::client::Service<bounty_service::BountyServiceImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> BountymeshClient
    for sails_rs::client::Actor<BountymeshClientProgram, E>
{
    type Env = E;
    fn bounty_service(
        &self,
    ) -> sails_rs::client::Service<bounty_service::BountyServiceImpl, Self::Env> {
        self.service(stringify!(BountyService))
    }
}
pub trait BountymeshClientCtors {
    type Env: sails_rs::client::GearEnv;
    /// Initialize the BountyMesh program.
    ///
    /// Owner = msg::source() (immutable for hackathon scope; AdminService lands later).
    /// protocol_fee_bps = 0 at launch.
    /// paused = false at launch.
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        min_reward: u128,
        auto_settle_blocks: u32,
    ) -> sails_rs::client::PendingCtor<BountymeshClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> BountymeshClientCtors
    for sails_rs::client::Deployment<BountymeshClientProgram, E>
{
    type Env = E;
    fn new(
        self,
        min_reward: u128,
        auto_settle_blocks: u32,
    ) -> sails_rs::client::PendingCtor<BountymeshClientProgram, io::New, Self::Env> {
        self.pending_ctor((min_reward, auto_settle_blocks))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (min_reward: u128, auto_settle_blocks: u32) -> ());
}

pub mod bounty_service {
    use super::*;
    pub trait BountyService {
        type Env: sails_rs::client::GearEnv;
        /// Accept the worker's submission. Poster's wallet-signed acknowledgement.
        ///
        /// Status flips Submitted → Accepted. NO value transfer — the reward stays in
        /// program escrow until the worker pulls it via Withdraw. Two-phase settlement
        /// per the PRD §5.2 redesign: Accept is the poster's signal, Withdraw is the
        /// worker's signal. Both are wallet-signed calls; both count toward the
        /// leaderboard's integrationsIn slice.
        ///
        /// Accept is not payable. Any attached value is refunded defensively.
        fn accept(&mut self, id: u64) -> sails_rs::client::PendingCall<io::Accept, Self::Env>;
        /// Cancel an Open bounty. Poster-only. Refunds the full escrow + any attached value.
        ///
        /// Status: Open → Cancelled (terminal).
        /// Caller MUST be the original poster.
        /// Refund: caller == value-target (poster), so `CommandReply::with_value(reward + value)`
        /// rides on the reply atomically.
        fn cancel(&mut self, id: u64) -> sails_rs::client::PendingCall<io::Cancel, Self::Env>;
        /// Claim an Open bounty. First wallet wins; second caller gets Err(BountyNotOpen).
        ///
        /// Claim is not payable. Any attached value is refunded defensively via
        /// CommandReply::with_value(value) on both Ok and Err branches.
        fn claim(&mut self, id: u64) -> sails_rs::client::PendingCall<io::Claim, Self::Env>;
        /// Post a new bounty. Payable: `msg::value()` must be >= reward; excess refunded.
        ///
        /// All error branches return `CommandReply::new(Err(...)).with_value(value)` so
        /// the caller's attached value rides back to them on the reply. Per
        /// `agent-paid-service.md` "Critical correctness note": `msg::send_bytes` does
        /// NOT fire on Err returns in sails-rs 0.10 — only the reply carries value atomically.
        fn post(
            &mut self,
            title: String,
            description: String,
            acceptance: String,
            reward: u128,
            deadline: Option<u32>,
            track: TrackEnum,
        ) -> sails_rs::client::PendingCall<io::Post, Self::Env>;
        /// Reject a Submitted bounty. Poster-only. Refunds the full escrow + any attached value.
        ///
        /// Status: Submitted → Rejected (terminal).
        /// Caller MUST be the original poster.
        /// The optional `reason` (≤ 500 chars) is persisted on-chain for indexer visibility.
        /// Refund: same primitive as Cancel — caller == value-target (poster).
        fn reject(
            &mut self,
            id: u64,
            reason: Option<String>,
        ) -> sails_rs::client::PendingCall<io::Reject, Self::Env>;
        /// Owner emergency: forcibly Revoke a bounty in any state.
        ///
        /// Caller MUST be `state.owner` (set immutably at construction).
        /// If bounty has not been withdrawn, escrow is pushed to the original poster.
        /// If bounty has already been withdrawn (Accepted + withdrawn=true), no
        /// escrow movement — status flip only.
        /// Refund: caller (owner) ≠ value-target (poster). Same primitive as Timeout:
        /// `msg::send_bytes` to poster + `with_value(value)` reply refund.
        fn revoke(&mut self, id: u64) -> sails_rs::client::PendingCall<io::Revoke, Self::Env>;
        /// Submit the worker's result payload + hash. Status flips Claimed → Submitted.
        ///
        /// Auth: caller must equal bounty.worker.
        /// Hash invariant: result_hash must be non-zero. All-zero H256 is rejected per
        /// the operator gotcha — workers generate hashes via `openssl dgst -sha256` over
        /// the payload bytes, never with a constant value.
        ///
        /// Submit is not payable. Any attached value is refunded defensively.
        fn submit(
            &mut self,
            id: u64,
            result_payload: String,
            result_hash: H256,
        ) -> sails_rs::client::PendingCall<io::Submit, Self::Env>;
        /// Permissionless watchdog: force a stuck bounty into TimedOut after deadline.
        ///
        /// Status: Open | Claimed | Submitted → TimedOut (terminal).
        /// Caller is anyone — this is the canonical permissionless watchdog pattern.
        /// Deadline MUST be set AND `exec::block_height() > deadline`.
        /// Refund: caller ≠ value-target (poster). Per the primitive rule, escrow is
        /// pushed to poster's mailbox via `msg::send_bytes(poster, [], reward)`;
        /// caller's attached value rides back on the reply via `with_value(value)`.
        /// This is the FIRST `msg::send_bytes` invocation in the contract surface.
        fn timeout(&mut self, id: u64) -> sails_rs::client::PendingCall<io::Timeout, Self::Env>;
        /// Worker pulls the escrowed reward. Two-phase settlement closure.
        ///
        /// Withdraw is the only method that:
        /// - Does NOT change bounty.status (bounty stays Accepted).
        /// - Does NOT touch index maps (status doesn't move).
        /// - DOES flip exactly one field (`bounty.withdrawn`).
        /// - DOES deliver value to the worker — combined with any defensive refund
        /// into a single `CommandReply::with_value(value + reward)`.
        ///
        /// Primitive choice: because Withdraw is worker-initiated (msg::source() ==
        /// bounty.worker == reward target), `CommandReply::with_value` is the correct
        /// primitive — it delivers value directly to the caller's balance on the
        /// reply. AutoSettle (caller ≠ target, deferred) would use `msg::send_bytes`
        /// for the same reason inverted. See PRD §8 Escrow integrity.
        ///
        /// Withdraw is not payable, but any attached value is refunded defensively
        /// alongside the reward in a single reply.
        /// Idempotency: a second call returns Err(AlreadyWithdrawn) without moving value.
        fn withdraw(&mut self, id: u64) -> sails_rs::client::PendingCall<io::Withdraw, Self::Env>;
    }
    pub struct BountyServiceImpl;
    impl<E: sails_rs::client::GearEnv> BountyService
        for sails_rs::client::Service<BountyServiceImpl, E>
    {
        type Env = E;
        fn accept(&mut self, id: u64) -> sails_rs::client::PendingCall<io::Accept, Self::Env> {
            self.pending_call((id,))
        }
        fn cancel(&mut self, id: u64) -> sails_rs::client::PendingCall<io::Cancel, Self::Env> {
            self.pending_call((id,))
        }
        fn claim(&mut self, id: u64) -> sails_rs::client::PendingCall<io::Claim, Self::Env> {
            self.pending_call((id,))
        }
        fn post(
            &mut self,
            title: String,
            description: String,
            acceptance: String,
            reward: u128,
            deadline: Option<u32>,
            track: TrackEnum,
        ) -> sails_rs::client::PendingCall<io::Post, Self::Env> {
            self.pending_call((title, description, acceptance, reward, deadline, track))
        }
        fn reject(
            &mut self,
            id: u64,
            reason: Option<String>,
        ) -> sails_rs::client::PendingCall<io::Reject, Self::Env> {
            self.pending_call((id, reason))
        }
        fn revoke(&mut self, id: u64) -> sails_rs::client::PendingCall<io::Revoke, Self::Env> {
            self.pending_call((id,))
        }
        fn submit(
            &mut self,
            id: u64,
            result_payload: String,
            result_hash: H256,
        ) -> sails_rs::client::PendingCall<io::Submit, Self::Env> {
            self.pending_call((id, result_payload, result_hash))
        }
        fn timeout(&mut self, id: u64) -> sails_rs::client::PendingCall<io::Timeout, Self::Env> {
            self.pending_call((id,))
        }
        fn withdraw(&mut self, id: u64) -> sails_rs::client::PendingCall<io::Withdraw, Self::Env> {
            self.pending_call((id,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Accept (id: u64) -> Result<(), super::Error>);
        sails_rs::io_struct_impl!(Cancel (id: u64) -> Result<(), super::Error>);
        sails_rs::io_struct_impl!(Claim (id: u64) -> Result<(), super::Error>);
        sails_rs::io_struct_impl!(Post (title: String, description: String, acceptance: String, reward: u128, deadline: Option<u32>, track: super::TrackEnum) -> Result<u64, super::Error>);
        sails_rs::io_struct_impl!(Reject (id: u64, reason: Option<String>) -> Result<(), super::Error>);
        sails_rs::io_struct_impl!(Revoke (id: u64) -> Result<(), super::Error>);
        sails_rs::io_struct_impl!(Submit (id: u64, result_payload: String, result_hash: H256) -> Result<(), super::Error>);
        sails_rs::io_struct_impl!(Timeout (id: u64) -> Result<(), super::Error>);
        sails_rs::io_struct_impl!(Withdraw (id: u64) -> Result<(), super::Error>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum BountyServiceEvents {
            BountyPosted {
                id: u64,
                poster: ActorId,
                reward: u128,
                track: TrackEnum,
                posted_at: u32,
                title: String,
                description: String,
                acceptance: String,
                deadline: Option<u32>,
            },
            BountyClaimed {
                id: u64,
                worker: ActorId,
                claimed_at: u32,
            },
            BountySubmitted {
                id: u64,
                worker: ActorId,
                result_hash: H256,
                submitted_at: u32,
            },
            BountyAccepted {
                id: u64,
                poster: ActorId,
                worker: ActorId,
                reward: u128,
                settled_at: u32,
            },
            BountyWithdrawn {
                id: u64,
                worker: ActorId,
                amount: u128,
                withdrawn_at: u32,
            },
            BountyCancelled {
                id: u64,
                by: ActorId,
                refunded: u128,
                cancelled_at: u32,
            },
            BountyRejected {
                id: u64,
                by: ActorId,
                worker: ActorId,
                reason: Option<String>,
                rejected_at: u32,
            },
            BountyTimedOut {
                id: u64,
                last_state: BountyStatus,
                called_by: ActorId,
                refunded_to: ActorId,
                timed_out_at: u32,
            },
            BountyRevoked {
                id: u64,
                by: ActorId,
                refunded_to: ActorId,
                revoked_at: u32,
            },
        }
        impl sails_rs::client::Event for BountyServiceEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "BountyPosted",
                "BountyClaimed",
                "BountySubmitted",
                "BountyAccepted",
                "BountyWithdrawn",
                "BountyCancelled",
                "BountyRejected",
                "BountyTimedOut",
                "BountyRevoked",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for BountyServiceImpl {
            type Event = BountyServiceEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Error {
    SelfLoop,
    MarketPaused,
    RewardBelowMinimum,
    InsufficientPayment,
    TitleTooLong,
    DescriptionTooLong,
    AcceptanceTooLong,
    PayloadTooLong,
    IdSpaceExhausted,
    BountyNotFound,
    BountyNotOpen,
    BountyNotClaimed,
    BountyNotSubmitted,
    BountyNotAccepted,
    AlreadyWithdrawn,
    Unauthorized,
    ZeroHashRejected,
    DeadlineNotReached,
    NoDeadlineSet,
    BountyAlreadyTerminal,
    ReasonTooLong,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum TrackEnum {
    Services,
    Social,
    Economy,
    Open,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum BountyStatus {
    Open,
    Claimed,
    Submitted,
    Accepted,
    Rejected,
    Cancelled,
    TimedOut,
    Revoked,
}
